l_english:
 PRODUCTION_PRODUCTION_LABEL:0 "生产"
 PRODUCTION_EQUIPMENTPOOL_LABEL:0 "储备"
 PRODUCTION_EFFICIENCY_LABEL:0 "§T效率§!"
 PRODUCTION_EQUIPMENT_LABEL:0 "装备"
 PRODUCTION_ADJUSTERS_LABEL:0 "适应"
 PRODUCTION_MATERIALS_LABEL:0 "材料"
 PRODUCTION_FACTORIES_LABEL:0 "工厂"
 PRODUCTION_OPERATIONAL_ARMS_FACTORIES_LABEL:0 "军用工厂"
 PRODUCTION_OPERATIONAL_DOCKYARDS_LABEL:0 "造船厂"
 PRODUCTION_OPERATIONAL_FACTORIES_LABEL:0 "民用工厂"
 PRODUCTION_AVAILABLE_ARMS_FACTORIES_LABEL:0 "空闲的军工厂"
 PRODUCTION_AVAILABLE_DOCKYARDS_LABEL:0 "空闲的船厂"
 PRODUCTION_AVAILABLE_FACTORIES_LABEL:0 "空闲的民用工厂"
 PRODUCTION_OPERATIONAL_FACTORIES_VALUE:0 "$VALUE$/$TOT$"
 PRODUCTION_MILITARY_LABEL:0 "§T陆军和空军装备§!"
 PRODUCTION_NAVAL_LABEL:0 "§T海军建造§!"
 PRODUCTION_BUILDINGS_LABEL:0 "§T建筑物建造§!"
 PRODUCTION_PRODUCING_DAILY:0 "$AMOUNT$/天"
 PRODUCTION_PRODUCING_WEEKLY:0 "$AMOUNT$/周"
 PRODUCTION_PRODUCING_MONTHLY:0 "$AMOUNT$/月"
 PRODUCTION_PRODUCING_YEARLY:0 "$AMOUNT$/年"
 PRODUCTION_PRODUCING_ETA_DATE:0 "完成时间: $DATE$"
 PRODUCTION_REPAIRING_ETA_DATE:0 "修复完成: $DATE$"
 PRODUCTION_PRODUCING_ETA_DAYS:0 "需 $AMOUNT$ 天"
 PRODUCTION_PRODUCING_ETA_WEEKS:0 "需 $AMOUNT$ 周"
 PRODUCTION_PRODUCING_ETA_MONTHS:0 "需 $AMOUNT$ 月"
 PRODUCTION_PRODUCING_ETA_YEARS:0 "需 $AMOUNT$ 年"
 PRODUCTION_PRODUCING_NEVER:0 "§R从不§!"
 PRODUCTION_PRODUCING_NO_FACTORIES:0 "§R未分配工厂§!"
 PRODUCTION_PRODUCING_NONE:0 "§R无§!"
 PRODUCTION_CAN_NOT_DEPLOY:0 "§R无法部署§!"
 PRODUCTION_CAN_NOT_DEPLOY_MANPOWER:0 "人力不足"
 PRODUCTION_INCREASE_PRIORITY_LABEL:0 "§G点击左键 §H增加优先级§!。\nShift+左键给予这个产品 §H最高优先级§!。§!"
 PRODUCTION_DECREASE_PRIORITY_LABEL:0 "§G点击左键 §H降低优先级§!。\nShift+左键给予这个产品 §H最低优先级§!。§!"
 PRODUCTION_PRIORITY_DELAYED:0 "一个有更高优先级的生产线将会比较低优先级的生产线优先获得原料。"
 PRODUCTION_EFFICIENCY:0 "£prod_eff  §T单位生产效率: $AMOUNT|H1%$§!"
 PRODUCTION_EFFICIENCY_MOD:0 "£prod_eff §T单位生产效率: $AMOUNT|Y1%$§!\n"
 PRODUCTION_EFFICIENCY_WITH_GAIN:0 "£prod_eff  §T单位生产效率: $AMOUNT|H1%$§! ($GAIN|H3%$ 每周)"
 PRODUCTION_EFFICIENCY_DESC:0 "§T平均工厂产品效率。\n在活跃的工厂里产品效率的增长依靠 $VALUE|H=2$%/单位生产均匀分配。§!"
 PRODUCTION_RESOURCE_PENALTY:0 "§T缺乏资源: $AMOUNT|R1%$§!"
 PRODUCTION_ASSIGN_EQUIPMENT:0 "§T选择装备开始生产。§!"
 PRODUCTION_MATERIALS_OIL:0 "原油"
 PRODUCTION_MATERIALS_ALUMINIUM:0 "铝"
 PRODUCTION_MATERIALS_RUBBER:0 "橡胶"
 PRODUCTION_MATERIALS_CHROMIUM:0 "铬"
 PRODUCTION_MATERIALS_STEEL:0 "钢"
 PRODUCTION_MATERIALS_TUNGSTEN:0 "钨"
 PRODUCTION_MATERIAL_VAL:0 "$VALUE|0H$"
 PRODUCTION_VEHICLES_BUTTON:0 "新增装甲车辆生产队列"
 PRODUCTION_VEHICLES_BUTTON_DISABLED:0 "装甲车辆 目前 §R未研发§!!"
 PRODUCTION_VEHICLES_BUTTON_NO_FACTORIES_DISABLED:0 "我们 §R没有军用工厂!!§"
 PRODUCTION_INFANTRY_BUTTON:0 "新增步兵和炮兵装备生产队列"
 PRODUCTION_INFANTRY_BUTTON_DISABLED:0 "步兵 & 炮兵装备 目前 §R未研发§!!"
 PRODUCTION_INFANTRY_BUTTON_NO_FACTORIES_DISABLED:0 "我们 §R没有军用工厂!!§"
 PRODUCTION_AIRCRAFT_BUTTON:0 "新增飞机生产队列"
 PRODUCTION_AIRCRAFT_BUTTON_DISABLED:0 "飞机 目前 §R未研发§!!"
 PRODUCTION_AIRCRAFT_BUTTON_NO_FACTORIES_DISABLED:0 "We have §RNo military factories§!!"
 PRODUCTION_SHIPS_BUTTON:0 "新增舰船生产队列"
 PRODUCTION_SHIPS_BUTTON_DISABLED:0 "船舶 目前 §R未研发§!!"
 PRODUCTION_SHIPS_BUTTON_NO_DEPLOY_DISABLED:0 "我们 §R没有港口§!!"
 PRODUCTION_SHIPS_BUTTON_NO_FACTORIES_DISABLED:0 "我们 §R没有造船厂§!!"
 PRODUCTION_CONSUMER_GOODS_VALUE:0 "$VALUE$"
 PRODUCTION_CONSUMER_GOODS:0 "生活消费品"
 PRODUCTION_CONSUMER_GOODS_LABEL:0 "§H生活消费品§!"
 PRODUCTION_CONSUMER_GOODS_DESC:0 "通过我们现行的经济政策, 人民期望我们有 $PERCENTAGE|H0%$ 的工厂用来生产日用消费品。 这个需求只能靠民用工厂来满足，此外剩下 $OPERATIONAL|H$ 工厂 $TRADE_USABLE|H$ 可用于贸易。"
 PRODUCTION_CIV_AND_MIL_FACTORIES:0 "民用和军用工厂: $KEY|H$"
 PRODUCTION_REQ_CONSUMER_GOODS_FACTORIES:0 "需要日用消费品工厂: $KEY|H$"
 PRODUCTION_MATERIAL_COST_DESC:0 "§T这个生产线使用 $AMOUNT|0H$ 单位的 $MATERIAL|H$。§!"
 PRODUCTION_MATERIAL_COST_LACKING_DESC:2 "§T需要额外的 $AMOUNT|0H$ 单位资源来达到最高效率最高效率。§!\n否则生产速度§R减慢§!。"
 PRODUCTION_LINE_CANCEL:0 "§G鼠标点击左键 §H取消§! 这个生产线。§!\n§GShift+鼠标左键 §H取消§! 所有生产线§!"
 PRODUCTION_CREATE_VARIANT:0 "§H更换为同类其他项目生产§!"
 PRODUCTION_CANCEL_CONSTRUCTION:0 "§T取消建造§!"
 PRODUCTION_VARIANT_OBSOLETE_YES:1 "重新委任"
 PRODUCTION_VARIANT_OBSOLETE_NO:1 "退役/解散"
 PRODUCTION_VARIANT_OBSOLETE_YES_DESC:0 "§G点击§!以将它标记为最新的装备。"
 PRODUCTION_VARIANT_OBSOLETE_NO_DESC:0 "§G点击§!以将它标记为过时的装备。"
 TRADE_FACTORIES_VALUE:0 "$VALUE$/$TOT$"
 CONFIRMCANCELPRODUCTIONLINE_TITLE:0 "取消该生产线"
 CONFIRMCANCELPRODUCTIONLINE_DESC:0 "你确定要 §R取消§! 该生产线?"
 CONFIRMCANCELALLPRODUCTIONLINE_TITLE:0 "§R取消所有的生产线§!"
 CONFIRMCANCELALLPRODUCTIONLINE_DESC:0 "你确定要 §R取消§! 所有的生产线?"
 CONFIRM_SWITCH_PRODUCTION_MODEL_TITLE:0 "切换生产装备"
 CONFIRM_SWITCH_PRODUCTION_MODEL_DESC:0 "你确定要 §R切换§! 生产的装备? 这将会让你失去 $DAYS|R$$ 的生产。"
 CONFIRMCANCELCONSTRUCTION_TITLE:0 "取消建造"
 CONFIRMCANCELCONSTRUCTION_DESC:0 "你确定要 §R取消§! 在 $REGION|H$ 的 $CONSTRUCTION|H$ ?"
 CONFIRMCANCELCONSTRUCTIONS_TITLE:0 "取消建造"
 CONFIRMCANCELCONSTRUCTIONS_DESC:0 "你确定要 §R取消§! 所有建造?"
 INFINITY:0 "£infinity_icon"
 PRODUCTION_EQUIPMENT_NEED:0 "需要: $AMOUNT|Y$"
 PRODUCTION_DEPLOY_TO_BASE:0 "部署到港口: $BASE|H$"
 PRODUCTION_DEPLOY_TO_FLEET:0 "部署到舰队: $FLEET|H$"
 PRODUCTION_NAVAL_DEPLOYMENT_FLEET_INVALID_BASE:0 "部署目标 $FLEET|H$ §R没有§!基地。"
 PRODUCTION_NAVAL_DEPLOYMENT_FLEET:0 "部署目标舰队 $FLEET|H$ 的基地在 $STATE|H$。"
 PRODUCTION_NAVAL_DEPLOYMENT_BASE:0 "部署目标的基地到 $STATE|H$。"
 PRODUCTION_NAVAL_DEPLOYMENT_INVALID_BASE:0 "没有部署目标。"
 PRODUCTION_NAVAL_DEPLOYMENT_NOT_DEPLOYABLE:0 "不能被部署e"
 PRODUCTION_NAVAL_DEPLOYMENT_AUTO_DEPLOYMENT:0 "自动部署"
 PRODUCTION_NAVAL_DEPLOYMENT_SCRAPPING:0 "报废"
 PRODUCTION_NAVAL_DEPLOYMENT_SCRAPPING_DESC:0 "没有有效的基地可供部署。 在完成之前单位将被取消。"
 PRODUCTION_NAVAL_DEPLOYMENT_STOCKPILING:0 "储备"
 PRODUCTION_RIGHT_CLICK_TO_ZOOM:0 "§G右键将镜头移至省份§!"
 WEEKLY_PRODUCTION:0 "周产量"
 PRODUCTION_WORKING_FACTORIES:0 "这是目前在你其中一条生产线上工作的工厂总数。"
 PRODICTION_MIC_TRANSFERED:0 "我们的$AMOUNT|Y$个工厂正在被$OVERLORD|Y$使用。"
 PRODICTION_MIC_RECEIVED_FROM_SUBJECT:0 "$AMOUNT|Y$个军用工厂来自于我们的附庸。"
 PRODICTION_MIC_SENT_TO_OVERLORD:0 "我们的$AMOUNT|R$个军用工厂供宗主国使用，我们只剩下了$LEFT|H$个。"
 PRODUCTION_CIVILIAN_FACTORIES_AVAILABLE:0 "空闲的建筑: $VALUE|Y$"
 PRODUCTION_CIVILIAN_FACTORIES_CURRENTLY:0 "使用中: $VALUE|Y$"
 PRODUCTION_MAX_EFFICIENCY_BASE:0 "基础生产效率上限: $VALUE|Y%$"
 PRODUCTION_MAX_EFFICIENCY_TOT:0 "£prod_eff_cap  生产效率上限系数: $VALUE|Y%$"
 PRODUCTION_MAX_EFFICIENCY_HINT:0 "£prod_eff_cap  生产效率上限系数决定工厂的 £prod_eff 生产效率，它通过 £tech_mod 科技研发来提高。"
 PRODUCTION_RESOURCES_PER_FACTORY:0 "§H每个工厂需要的资源:§!"
 PRODUCTION_MATERIAL_NO_WASTE:0 "生产线没有浪费任何资源"
 PRODUCTION_MATERIAL_WASTE:0 "生产线浪费了 $WASTE|R2$ 单位资源。"
 PRODUCTION_SPEED:0 "生产速度: $SPEED|Y$"
 PRODUCTION_SPEED_MODIFIERS:0 "§Y生产速度修正:§!"
 INDUSTRIAL_CAPACITY_FACTOR:0 "工厂产出系数: $VALUE|Y$"
 INDUSTRIAL_CAPACITY_FACTOR_MODIFIERS:0 "工厂产出系数修正:"
 INDUSTRIAL_PROGRESS:0 "$CONSTRUCTION|H$ 完成进度： $PROGRESS|0H$/$COST|0H$ ( $VALUE|0%H$ ) "
 INDUSTRIAL_PROGRESS_REPAIR:0 "$CONSTRUCTION|H$ 修复进度: $PROGRESS|%0H$"
 INDUSTRIAL_BASE_FACTORY_OUTPUT:0 "基础工厂产出: $VALUE|H$"
 INDUSTRIAL_BASE_SPEED:0 "来自 $FACTORIES|0H$ 工厂的产出: $VALUE|H$"
 PROD_COST_VALUE:0 "£production_cost  $VALUE$"
 NAVPROD_COST_VALUE:0 "£navprod_cost  $VALUE$"
 PRODUCTION_CIVILIAN_FACTORIES_OWNED:0 "拥有: $VAL|H$"
 PRODUCTION_CIVILIAN_FACTORIES_BORROWED:0 "源自出口: $VAL|H$"
 PRODUCTION_CIVILIAN_FACTORIES_FROM_SUBJECTS:0 "源自附庸 +$VAL|H$"
 PRODUCTION_CIVILIAN_FACTORIES_SENT_TO_MASTER:0 "给宗主国: $VAL|R$"
 PRODUCTION_CIVILIAN_FACTORIES_FROM_OTHERS:0 "From other countries: +$VAL|H$"
 PRODUCTION_CIVILIAN_FACTORIES_SENT_TO_OTHERS:0 "Given to other countrues: $VAL|R$"
 PRODUCTION_CIVILIAN_FACTORIES_DAMAGED:0 "Damaged: $VAL|R$"
 PRODUCTION_EQUIPMENT_TOTAL_NEED:0 "总需求: $VALUE|0Y$"
 PRODUCTION_EQUIPMENT_TOTAL_NEED_FILLED:0 "总需求: §G已满足§!"
 PRODUCTION_EQUIPMENT_TOTAL_NEED_UPGRADE:0 "升级需求: $VALUE|0Y$"
 PRODUCTION_EQUIPMENT_DAILY_BALANCE:0 "日常供需结算: $VALUE|=2Y$"
 PRODUCTION_EQUIPMENT_FILL_ESTIMATION:0 "根据目前日常供需结算，我们在 $VALUE|0Y$ 天内将会§Y满足§!需求。"
 PRODUCTION_EQUIPMENT_FILLED:0 "现在我们的需求 §G已满足§!。"
 PRODUCTION_EQUIPMENT_LOSSES:0 "昨天我们损失了 $VALUE|R$ 装备。"
 PROD_LINE_PLANE_DEST_RESERVES:0 "这个队列生产的飞机会被储存"
 PROD_LINE_PLANE_DEST_UPGRADING:0 "这个队列生产的飞机被用于升级"
 PROD_LINE_PLANE_DEST_REINFORCEMENT:0 "这个队列生产的飞机被用于增援"
 PROD_LINE_LAND_DEST_RESERVES:0 "这个队列生产的装备会被储存"
 PROD_LINE_LAND_DEST_UPGRADING:0 "这个队列生产的装备被用于升级"
 PROD_LINE_LAND_DEST_REINFORCEMENT:0 "这个队列生产的装备被用于增援"
 CONFIRM_REMOVE_BUILDING_LEVEL_TITLE:0 "移除建筑"
 CONFIRM_REMOVE_BUILDING_LEVEL_DESC:0 "你确定要§R移除§!这个建筑?"
 CONFIRM_REMOVE_CONSTRUCTION_LEVEL_TITLE:0 "取消建设"
 CONFIRM_REMOVE_CONSTRUCTION_LEVEL_DESC:0 "你确定要§R取消§!建设?"
 CONFIRM_REMOVE_CONVERSION_LEVEL_TITLE:0 "取消转换"
 CONFIRM_REMOVE_CONVERSION_LEVEL_DESC:0 "你确定要§R取消§ 转换?"
 CONFIRM_ADD_CONVERSION_LEVEL_TITLE:0 "开始转换"
 CONFIRM_ADD_CONVERSION_LEVEL_DESC:0 "你确定要§G转换§!这个建筑?"
 PRODUCTION_EFFICIENCY_GAIN_BASE:0 "每天基础积累: $VAL|%Y$"
 PRODUCTION_RESOURCE_FACTOR:0 "缺乏资源: $VAL|%+$"
 PRODUCTION_OUTPUT_EXPLAIN:0 "我们的 $FACTORIES|Y$ £factory_item  军工厂提供 $OUTPUT|Y$ £production_cost 。 \n$ITEM|Y$ 需要消耗 $ITEM_COST|2Y$ £production_cost , 这让我们可以生产 $PERTIMEPERIOD$。\n"
 PRODUCTION_OUTPUT_EXPLAIN_NAVAL:0 "我们的 $FACTORIES|Y$ £naval_factory_icon  造船厂提供 £navprod_cost $OUTPUT|Y$。\n$ITEM|Y$ 需要消耗 $ITEM_COST|2Y$ £navprod_cost , 这让我们可以生产 $PERTIMEPERIOD$。\n"
 PRODUCTION_UNITS_PER_DAY:0 "$UNITS|Y$ 单位/天"
 PRODUCTION_UNITS_PER_WEEK:0 "$UNITS|Y$ 单位/周"
 PRODUCTION_UNITS_PER_MONTH:0 "$UNITS|Y$ 单位/月"
 PRODUCTION_UNITS_PER_YEAR:0 "$UNITS|Y$ 单位/年"
 PRODUCTION_FACTORY_ASSIGN_DESC:0 "点击指派 £factory_item $FACTORIES|Y$ 军工厂至此生产线，每天提高 £production_cost $OUTPUT|Y$ 的产量。"
 PRODUCTION_DOCKYARD_ASSIGN_DESC:0 "点击指派 £naval_factory_icon $FACTORIES|Y$ 海军造船厂至此生产线，每天提高 £navprod_cost $OUTPUT|Y$ 的产量。"
 PRODUCTION_BASE_OUTPUT:0 "基础产出: $VALUE|Y$ x$MUL$"
 PRODUCTION_EFF_GAIN_HINT:0 "§Y影响生产效率累积的各种因素:§!"
 CARRIER_AIR_WING_COMPOSITION_TITLE:0 "为航母配置默认的空军联队"
 CARRIER_AIR_WING_LIMIT_UNDER:0 "$COUNT|Y$/$LIMIT$"
 CARRIER_AIR_WING_LIMIT_MATCH:0 "$COUNT|G$/$LIMIT$"
 CARRIER_AIR_WING_LIMIT_OVER:0 "$COUNT|R$/$LIMIT$"
 CARRIER_AIR_WING_LIMIT_DESC:0 "飞机/航母容量"
 CARRIER_AIR_WING_LIMIT_DESC_UNDER:0 "§G这个航母未满载§!"
 CARRIER_AIR_WING_LIMIT_DESC_OVER:0 "§R这个航母已超载，飞机作战效率将会遭受惩罚§!"
 CARRIER_AIR_WING_INCREASE:0 "增加总数\n§GCtrl+左键来增加§! §H5§!\n§GShift+左键来增加§! §H10§!"
 CARRIER_AIR_WING_DECREASE:0 "降低总数\n§GCtrl+左键来减少§! §H5§!\n§GShift+左键来减少§! §H10§!"
 PRODUCTION_ENTRY_NEW:0 "§G全新§!"
 PRODUCTION_ENTRY_OUTDATED:0 "§H过时§!"
 PRODUCTION_LINE_CHANGE:0 "§G点击 §H改变§! 正在生产的装备。\n如果你转换成同一种类型的更新装备，可以保留一部分效率的积累。\n§!§R切换生产的装备会损失这个队列已生产一半的产品。§!"
 PRODUCTION_LINE_CHANGE_NAVAL:0 "§G点击§H改变§! 生产装备.\n§!§R你将失去所有积累的生产效率.§!"
 PRODUCTION_EQUIPMENT_FILTER:0 "步兵 & 炮兵装备"
 PRODUCTION_ARMOR_FILTER:0 "装甲车辆"
 PRODUCTION_AIR_FILTER:0 "空军单位"
 PRODUCTION_CAPITAL_SHIPS_FILTER:0 "主力舰船"
 PRODUCTION_SCREEN_SHIPS_FILTER:0 "驱逐舰与轻巡"
 PRODUCTION_OTHER_SHIPS_FILTER:0 "其他种类舰船"
 PRODUCTION_LACKING_RESOURCES_FILTER:0 "Fulfilled Resources"
 PRODUCTION_STOCKPILING_FILTER:0 "Stockpiling"
 PRODUCTION_REINFORCING_FILTER:0 "Reinforcing"
 PRODUCTION_UPGRADING_FILTER:0 "Upgrading"
 PRODUCTION_OUTDATED_FILTER:0 "Up to date models"
 PRODUCTION_FILTER_CLICK_TO_HIDE:0 "§GClick§! to §Rhide§! all of this category."
 PRODUCTION_FILTER_CLICK_TO_SHOW:0 "§GClick§! to §Gshow§! all of this category."
 PRODUCTION_FILTER_SHIFTCLICK:0 "§GShift+点击§! 查看."
 PRODUCTION_FILTER_SHIFTCLICK_AGAIN:0 "\n§GShift+Click§! to §Gshow§! everything again."
 PRODUCTION_FILTER_RIGHTCLICK:0 "\n§GRight Click§! to toggle collapsing all of this category."
 PRODUCTION_FILTER_ARMS_FACTORIES:0 "使用中的军工厂"
 PRODUCTION_FILTER_DOCKYARDS:0 "使用中的海军造船厂"
 PRODUCTION_DRAG_N_DROP:0 "§GDrag and drop§! to change the §Ypriority§!."
 PRODUCTION_COLLAPSE:0 "§GClick§! to §Ycollapse§!."
 PRODUCTION_EXPAND:0 "§GClick§! to §Yexpand§!."
 PRODUCTION_FACTORY_SCALE_UP:0 "§GClick§! to scale up to §Y$SCALE$x§! view."
 PRODUCTION_FACTORY_SCALE_DOWN:0 "§GClick§! again to scale down to §Y1x§! view."
 PRODUCTION_ADD_FACTORIES_CLICK:0 "§GClick§! to add §Y+1§!\n§GCtrl + Click§! to add §Y+5§!\n§GShift + Click§! to add §Y+10§!"
 PRODUCTION_SUB_FACTORIES_CLICK:0 "§GClick§! to substract §Y-1§!\n§GCtrl + Click§! to substract §Y-5§!\n§GShift + Click§! to substract §Y-10§!"
 PRODUCTION_CLICK_TO_APPEND_OR_INSERT:0 "§GClick§! to append new production line at the end.\n§GShift + Click§! to put a new production line at the top."
 PRODUCTION_NAVAL_DEPLOYMENT_STATE_NAME:0 "$STATE$ ($LVL|Y$)"
 PRODUCTION_LINE_CONVERT_NO_EQUIPMENT_IN_STOCK:0 "§R目前没有我们可以转换的装备: $VARIANT|H$§!"
 PRODUCTION_LINE_CONVERT_HEADER:0 "从库存转换"
 PRODUCTION_LINE_CONVERT_ORDER_OF_CONVERSION:0 "转换顺序:"
 PRODUCTION_LINE_CONVERT_ORDER_OF_CONVERSION_ENTRY:0 "\n  $NUM|Y2$ 的 $VARIANT|G$ ($TYPE$) 成本: "
 PRODUCTION_LINE_CONVERT_ORDER_OF_CONVERSION_FREE_ENTRY:0 "\n  $NUM|Y2$ 的 $VARIANT|G$ ($TYPE$)"
 PRODUCTION_LINE_CONVERT_RESOURCE_COST_ENTRY:0 "$NUM$£resources_strip|$FRAME$ "
 PRODUCTION_LINE_CONVERT_DESC:0 "Convert from stockpile will use basic vehicles within the stockpile and convert them into modified vehicles requested from the current production line at a reduced cost. This will continue until the stockpile is empty."
 PRODUCTION_LINE_CONVERT_SPEED_TOTAL:0 "转换速度: §G+§!$SPD|G%0$"
 PRODUCTION_LINE_CONVERT_SPEED_BASE:0 "基础: $VAL|Y0%$"
 PRODUCTION_LINE_CONVERT_RES_NEED:0 " $NAME|Y$转换成本:"
 PRODUCTION_LINE_CONVERT_RES_NEED_ENTRY:0 "\n   £resources_strip|$FRAME$: ($NEW|Y0$-$OLD|G0$)=$SUM|R0$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_TOTAL_SIMPLE:0 "§H许可证生产§!: $VALUE|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_TOTAL:0 "§H许可证生产工厂产出§!\n总共: $VALUE|+%$\n损坏:"
 LICENSED_EQUIPMENT_TECH_SPEED_REDUCTION:0 "§Y许可证技术差异§!: $TOTAL|+%$\n基础: $BASE|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_MODIFIER:0 "§Y许可证因素§!: $TOTAL|+%$\n基础: $BASE|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_NOT_FACTION:0 "§Y与许可方不在同一阵营§!: $VALUE|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_NO_LICENSE:0 "§Y没有许可证§!: $VALUE|+%$"
 LICENSED_PURCHASE_CIC_COST:0 "§Y此许可花费§!: $AMOUNT|Y$£civ_factory_output"
 PRODUCTION_AIRCRAFT_BUTTON_BUTTON_NO_FACTORIES_DISABLED:0 "我们 §R没有军用工厂!!§"
